# Use the base Debian image produced by the Dev Containers project.
# For the latest releases, see the README https://github.com/devcontainers/images/tree/main/src/base-debian
FROM mcr.microsoft.com/devcontainers/base:debian-11

# Copy over the Intellij IDEA distribution. You need to manually download the distribution and place it in the given
# directory or else this copy command will fail.
COPY idea-distribution/ /opt/idea
